### PR TITLE
0.19

### PR DESCRIPTION
**Pull request by zgohr**

### CODE REVIEW

**Comment by zgohr** [comment]
Are there plans for this lib to be upgraded to Elm 0.19?

**Comment by tylerthehaas** [comment]
I was going to open a similar pull request before I saw this one. Any chance this gets merged in soon?

**Comment by zgohr** [comment]
If this doesn't get merged and published I'll publish my fork in a week or so, as I need it for my upgrade. If anyone needs it sooner let me know and I'll make it happen.

**Comment by tylerthehaas** [comment]
I jusg need it for a new project I've recently started. I'm happy to wait a week though. It'd be a shame to have to create a second fork of this project.

**Comment by isaacseymour** [comment]
@zgohr would you be willing to publish your fork? I think it's the last thing blocking my upgrade 😄

**Comment by zgohr** [comment]
`zgohr/elm-csv` is now published with v1.0.0 for elm 0.19

**Comment by lovasoa** [comment]
Great, thank you very much ! I am updating this today. Sorry for the delay.

**Comment by lovasoa** [comment]
Here it is : https://package.elm-lang.org/packages/lovasoa/elm-csv/latest/Csv

Thank you very much, @zgohr ! Can you please add a few words to the readme of your fork, and a link to [`lovasoa/elm-csv`](https://package.elm-lang.org/packages/lovasoa/elm-csv/latest), in order for people finding your fork on package.elm-lang.org not to get confused ?

**Comment by zgohr** [comment]
Yes, thank you for publishing!

**Pull request merged**
